# Generated by Django 3.0.6 on 2020-07-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_comment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
