# Generated by Django 3.0.6 on 2020-07-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_auto_20200718_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
